// Deterministic, dependency-free bundle. The existing HTTP asset allowlist is unchanged.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('../public/', import.meta.url);
const read = name => readFile(new URL(name, root), 'utf8');
const strip = source => source.replace(/^import .*?;\n/gm, '').replace(/^export /gm, '');
const imports = "import { TownScene, avatar } from './scene.js';\nimport { StudioLayout, WIDTH, HEIGHT } from './layout.js';\n";
const app = '// Generated by npm run build. Edit client.js, overview.js or lifecycle.js instead.\n' + imports +
  (await Promise.all(['lifecycle.js', 'overview.js', 'client.js'].map(read))).map(strip).join('\n');
const css = '/* Generated by npm run build. Edit base.css or studio.css instead. */\n' +
  (await Promise.all(['base.css', 'studio.css'].map(read))).join('\n');
for (const [name, text] of [['app.js', app], ['styles.css', css]]) {
  const path = new URL(name, root);
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== text) throw new Error(`Stale bundle ${fileURLToPath(path)}; run npm run build`);
  } else await writeFile(path, text);
}
